# Generated by Django 3.1.7 on 2021-04-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='state',
        ),
    ]
