# Generated by Django 3.1.7 on 2021-04-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210402_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='address1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
