# Generated by Django 3.1.7 on 2021-04-30 01:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50, verbose_name='Full Name')),
                ('address1', models.CharField(max_length=100, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='', max_length=21, verbose_name='State')),
                ('zipCode', models.CharField(default='', max_length=9, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Zip Code')),
            ],
        ),
        migrations.CreateModel(
            name='fuelQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallonsRequested', models.IntegerField(default=0, verbose_name='Gallons Requested')),
                ('deliveryAddress', models.CharField(blank=True, default='', max_length=100, verbose_name='Delivery Address')),
                ('deliveryDate', models.DateField(verbose_name='Delivery Date')),
                ('suggestedPrice', models.DecimalField(decimal_places=7, default=Decimal('0.00000'), max_digits=100, verbose_name='Suggested Price per Gallon')),
                ('totalAmount', models.DecimalField(decimal_places=7, default=Decimal('0.00000'), max_digits=100, verbose_name='Total Amount')),
                ('username', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('verify_password', models.CharField(max_length=25)),
            ],
        ),
    ]
