# Generated by Django 3.1.7 on 2021-04-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='fuelQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallonsRequested', models.IntegerField(default=0)),
                ('deliveryAddress', models.CharField(max_length=40)),
                ('suggestedPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
